eureka:
  client:
    service-url:
      defaultZone: http://tjr:tjr1234QWER@localhost:8080/eureka/,http://tjr:tjr1234QWER@localhost:8081/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
