eureka:
  client:
    service-url:
      defaultZone: http://hi:ruben@localhost:19990/eureka/,http://hi:ruben@localhost:19991/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: gues